// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnX-9rFy4eS7haWOmhtRwHyY_QweIvSvI',
    appId: '1:970762241705:web:dbcd1cb80f2521ed4f0bb8',
    messagingSenderId: '970762241705',
    projectId: 'todolist-89438',
    authDomain: 'todolist-89438.firebaseapp.com',
    storageBucket: 'todolist-89438.appspot.com',
    measurementId: 'G-FP9J26N0RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5i4b5YyS63NXG0x2rxL8KCwaSZqyRNx0',
    appId: '1:970762241705:android:f8a13a188a812def4f0bb8',
    messagingSenderId: '970762241705',
    projectId: 'todolist-89438',
    storageBucket: 'todolist-89438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkW-Q4JCSUVaZ7vdrL-ElH_DDNV52zes',
    appId: '1:970762241705:ios:9590d5d64deeb72a4f0bb8',
    messagingSenderId: '970762241705',
    projectId: 'todolist-89438',
    storageBucket: 'todolist-89438.appspot.com',
    iosClientId: '970762241705-ln4kthugdj59ol4cumgqpbh3k37c188i.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho5Final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrkW-Q4JCSUVaZ7vdrL-ElH_DDNV52zes',
    appId: '1:970762241705:ios:9590d5d64deeb72a4f0bb8',
    messagingSenderId: '970762241705',
    projectId: 'todolist-89438',
    storageBucket: 'todolist-89438.appspot.com',
    iosClientId: '970762241705-ln4kthugdj59ol4cumgqpbh3k37c188i.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho5Final',
  );
}
